version: '3'
services:
  blog_sonpike:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - sonpike

networks:
  sonpike:
    external: true
